# Generated by Django 6.0.7 on 2026-07-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
