# Generated by Django 5.1.4 on 2026-07-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_completion_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
