# Generated by Django 5.1.4 on 2026-07-28 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
