# Generated by Django 5.1.4 on 2026-08-11 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_title', models.CharField(default='OpsPortal Enterprise', max_length=255)),
                ('environment_stage', models.CharField(choices=[('prod', 'Production (Live Webhooks)'), ('staging', 'Staging Canary'), ('dev', 'Development Sandbox')], default='prod', max_length=20)),
                ('fallback_api_url', models.URLField(blank=True, default='')),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('slack_webhooks_enabled', models.BooleanField(default=False)),
                ('mfa_enforced', models.BooleanField(default=True)),
                ('secret_key_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
