# Generated by Django 5.1.4 on 2026-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_avatar_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
